# GitHub Project Configuration for Nexus
# This file defines the project structure, labels, and milestones

project:
  name: "Nexus Development"
  description: "AI-First Business Operating System Development Tracking"
  
labels:
  # Priority Labels
  - name: "priority-critical"
    color: "d73a4a"
    description: "Critical issue that blocks other work"
  - name: "priority-high"
    color: "ff9500"
    description: "High priority issue for current milestone"
  - name: "priority-medium"
    color: "fbca04"
    description: "Medium priority - nice to have"
  - name: "priority-low"
    color: "0e8a16"
    description: "Low priority - future consideration"
    
  # Component Labels
  - name: "ai-system"
    color: "8b5cf6"
    description: "AI, chat, agents, and ML components"
  - name: "integration"
    color: "0969da"
    description: "Third-party integrations and APIs"
  - name: "ui-ux"
    color: "d1ecf1"
    description: "User interface and experience"
  - name: "database"
    color: "1f883d"
    description: "Database, migrations, and data"
  - name: "security"
    color: "e99695"
    description: "Security, authentication, and compliance"
  - name: "infrastructure"
    color: "5a32a3"
    description: "Deployment, CI/CD, and infrastructure"
    
  # Pillar Labels
  - name: "pillar-1-core-ai"
    color: "7c3aed"
    description: "Core AI & Chat System (Pillar 1)"
  - name: "pillar-2-business-intelligence"
    color: "059669"
    description: "Business Intelligence & Automation (Pillar 2)"
  - name: "pillar-3-integrations"
    color: "0ea5e9"
    description: "Integrations & Storage (Pillar 3)"
  - name: "pillar-4-user-experience"
    color: "f59e0b"
    description: "User Experience & Onboarding (Pillar 4)"
  - name: "pillar-5-security"
    color: "ef4444"
    description: "Security & Infrastructure (Pillar 5)"
    
  # Type Labels
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or enhancement"
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "task"
    color: "7057ff"
    description: "Development task or work item"
  - name: "documentation"
    color: "0075ca"
    description: "Documentation improvements"
  - name: "needs-triage"
    color: "ededed"
    description: "Needs initial review and labeling"
    
milestones:
  # Sprint Milestones
  - name: "Sprint - Current"
    description: "Current sprint work in progress"
    due_date: "2025-02-15"
    
  - name: "Sprint - Next"
    description: "Next sprint planning"
    due_date: "2025-03-01"
    
  # Pillar Milestones
  - name: "Pillar 1 - Core AI"
    description: "Supervisor Agent, Domain Agents, Context Chips"
    due_date: "2025-03-15"
    
  - name: "Pillar 2 - Business Intelligence"
    description: "Live KPIs, Business Health Score, Automation Recipes"
    due_date: "2025-04-01"
    
  - name: "Pillar 3 - Integrations"
    description: "Storage Connectors, QuickBooks, Enhanced OAuth"
    due_date: "2025-04-15"
    
  - name: "Pillar 4 - User Experience"
    description: "Unified Inbox, Help Site, Guided Tour"
    due_date: "2025-05-01"
    
  - name: "Pillar 5 - Security & Infrastructure"
    description: "Security Enhancements, Performance, Monitoring"
    due_date: "2025-05-15"
    
  # Release Milestones
  - name: "MVP Release"
    description: "Minimum Viable Product release"
    due_date: "2025-06-01"
    
  - name: "Beta Release"
    description: "Beta version with key features"
    due_date: "2025-07-01"

views:
  - name: "Current Sprint"
    description: "Active development work"
    filters:
      milestone: "Sprint - Current"
      state: "open"
      
  - name: "Backlog"
    description: "Prioritized backlog items"
    filters:
      state: "open"
      no_milestone: true
      
  - name: "Critical Issues"
    description: "High priority issues requiring immediate attention"
    filters:
      labels: ["priority-critical"]
      state: "open"
      
  - name: "AI Development"
    description: "AI and ML related development"
    filters:
      labels: ["pillar-1-core-ai", "ai-system"]
      state: "open"
      
  - name: "Integration Work"
    description: "Third-party integrations and APIs"
    filters:
      labels: ["pillar-3-integrations", "integration"]
      state: "open" 