# Build stage
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./
COPY pnpm-lock.yaml ./
RUN npm install -g pnpm

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy source code
COPY . .

# Environment variables for build (these will be replaced at build time)
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPABASE_SERVICE_ROLE_KEY
ARG VITE_STRIPE_PUBLISHABLE_KEY
ARG VITE_STRIPE_WEBHOOK_SECRET
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_GOOGLE_CLIENT_SECRET
ARG VITE_MICROSOFT_CLIENT_ID
ARG VITE_MICROSOFT_CLIENT_SECRET
ARG VITE_HUBSPOT_CLIENT_ID
ARG VITE_HUBSPOT_CLIENT_SECRET
ARG VITE_PAYPAL_CLIENT_ID
ARG VITE_PAYPAL_ENV
ARG VITE_OPENROUTER_API_KEY
ARG VITE_N8N_URL
ARG VITE_N8N_API_KEY
ARG VITE_NINJARMM_CLIENT_ID
ARG VITE_MS_TEAMS_TENANT_ID
ARG VITE_BRAVE_API_KEY
ARG VITE_NEXT_PUBLIC_APP_URL
ARG VITE_DEV_APP_URL
ARG VITE_SLACK_CLIENT_ID
ARG VITE_GOOGLE_API_KEY
ARG VITE_CHAT_V2
ARG VITE_AI_CHAT_URL

# Set environment variables for build
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_SUPABASE_SERVICE_ROLE_KEY=$VITE_SUPABASE_SERVICE_ROLE_KEY
ENV VITE_STRIPE_PUBLISHABLE_KEY=$VITE_STRIPE_PUBLISHABLE_KEY
ENV VITE_STRIPE_WEBHOOK_SECRET=$VITE_STRIPE_WEBHOOK_SECRET
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_GOOGLE_CLIENT_SECRET=$VITE_GOOGLE_CLIENT_SECRET
ENV VITE_MICROSOFT_CLIENT_ID=$VITE_MICROSOFT_CLIENT_ID
ENV VITE_MICROSOFT_CLIENT_SECRET=$VITE_MICROSOFT_CLIENT_SECRET
ENV VITE_HUBSPOT_CLIENT_ID=$VITE_HUBSPOT_CLIENT_ID
ENV VITE_HUBSPOT_CLIENT_SECRET=$VITE_HUBSPOT_CLIENT_SECRET
ENV VITE_PAYPAL_CLIENT_ID=$VITE_PAYPAL_CLIENT_ID
ENV VITE_PAYPAL_ENV=$VITE_PAYPAL_ENV
ENV VITE_OPENROUTER_API_KEY=$VITE_OPENROUTER_API_KEY
ENV VITE_N8N_URL=$VITE_N8N_URL
ENV VITE_N8N_API_KEY=$VITE_N8N_API_KEY
ENV VITE_NINJARMM_CLIENT_ID=$VITE_NINJARMM_CLIENT_ID
ENV VITE_MS_TEAMS_TENANT_ID=$VITE_MS_TEAMS_TENANT_ID
ENV VITE_BRAVE_API_KEY=$VITE_BRAVE_API_KEY
ENV VITE_NEXT_PUBLIC_APP_URL=$VITE_NEXT_PUBLIC_APP_URL
ENV VITE_DEV_APP_URL=$VITE_DEV_APP_URL
ENV VITE_SLACK_CLIENT_ID=$VITE_SLACK_CLIENT_ID
ENV VITE_GOOGLE_API_KEY=$VITE_GOOGLE_API_KEY
ENV VITE_CHAT_V2=$VITE_CHAT_V2
ENV VITE_AI_CHAT_URL=$VITE_AI_CHAT_URL

# Build the application
RUN pnpm run build

# Production stage - use a simple HTTP server
FROM node:20-alpine

# Install serve and curl for health check
RUN npm install -g serve && apk add --no-cache curl

# Copy built application
COPY --from=builder /app/dist /app/dist

# Expose port
EXPOSE 3000

# Health check (works with both HTTP and HTTPS)
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:3000/ || exit 1

# Start the server (bind to all interfaces for Traefik)
CMD ["serve", "-s", "/app/dist", "-l", "tcp://0.0.0.0:3000"] 