version: '3.8'

services:
  # PostgreSQL with pgvector extension
  pgvector-17:
    image: pgvector/pgvector:pg17
    container_name: pgvector-17
    ports:
      - "5433:5432"  # Maps host port 5433 to container port 5432
    environment:
      POSTGRES_DB: vector_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - bf793f3a6ff65c3de96f926c2e82994fbd7c5550eff60630ac0130a05a51ad92:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d  # Optional: for initial migrations
    restart: unless-stopped
    networks:
      - nexus-network

  # Redis for caching and BullMQ job queues
  redis:
    image: redis:7-alpine
    container_name: nexus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - nexus-network

volumes:
  bf793f3a6ff65c3de96f926c2e82994fbd7c5550eff60630ac0130a05a51ad92:
    external: true
  redis_data:
    driver: local

networks:
  nexus-network:
    driver: bridge 