version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - api

  api:
    build: ./server
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/nexus
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexus
    ports:
      - "5432:5432"
    volumes:
      - nexus-db-data:/var/lib/postgresql/data

volumes:
  nexus-db-data: 