

services:
  # ------------------------------
  # Backend API (Node.js server)
  # ------------------------------
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nexus-server
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - nexus-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ------------------------------
  # Frontend (Vite + Nginx)
  # ------------------------------
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nexus-frontend
    env_file:
      - ./client/.env
    ports:
      - "5173:80"   # Expose the Nginx-served app on host 5173
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - nexus-network

  # ------------------------------
  # Redis for caching and session storage
  # ------------------------------
  redis:
    image: redis:7-alpine
    container_name: nexus-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --maxmemory
      - "${REDIS_MAX_MEMORY:-256mb}"
      - --maxmemory-policy
      - allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nexus-network

  # ------------------------------
  # (Optional) pgAdmin UI
  # ------------------------------
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nexus-pgadmin
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@nexus.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - nexus-network
    profiles:
      - admin

  # ------------------------------
  # Postgres (pgvector image)
  # ------------------------------
  postgres:
    image: pgvector/pgvector:pg17
    container_name: nexus-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nexus_db}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./config/postgres/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nexus-network

volumes:
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
  pg_data:
    driver: local

networks:
  nexus-network:
    driver: bridge
    name: nexus-network