version: '3.8'

services:

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: nexus-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server 
      --appendonly yes 
      --maxmemory ${REDIS_MAX_MEMORY:-256mb} 
      --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nexus-network

  # Development database admin (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nexus-pgadmin
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@nexus.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nexus-network
    profiles:
      - admin

volumes:
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  nexus-network:
    driver: bridge
    name: nexus-network