/*
 * Central route map for title / breadcrumb generation
 * Extend as new routes are added.
 */
export const ROUTELABELS: Record<string, string> = {
  '/dashboard': 'Dashboard',
  '/chat': 'Chat',
  '/mobile': 'Mobile App',

  '/ai-chat': 'AI Chat',
  '/ai-hub': 'AI Hub',
  '/ai-capabilities': 'AI Capabilities',
  '/ai-performance': 'AI Performance',
  '/ai-settings': 'AI Settings',
  '/ai-model': 'AI Model',
  '/ai-agent': 'AI Agent',
  '/workspace': 'Workspace',
  '/integrations/api-learning': 'API Learning System',
  '/integrations/marketplace': 'Integration Marketplace',
  '/settings': 'Settings',
  '/settings/profile': 'Profile',
  '/settings/security': 'Security',
  '/settings/billing': 'Billing',
  '/settings/integrations': 'Integrations',
  '/operations': 'Operations',
  '/operations/analytics': 'Operations Analytics',
  '/finance': 'Finance',
  '/finance/operations': 'Financial Operations',
  '/sales': 'Sales',
  '/sales/performance': 'Sales Performance',
  '/marketing': 'Marketing',
  '/marketing/analytics': 'Marketing Analytics',
  '/support': 'Support',
  '/support/analytics': 'Support Analytics',
  '/maturity': 'Maturity',
  '/maturity/analytics': 'Maturity Analytics',
  '/analytics': 'Analytics',
  '/analytics/unified': 'Unified Analytics',
  '/analytics/data-warehouse': 'Data Warehouse',
  '/analytics/integrations': 'Analytics Integrations',
  '/analytics/showcase': 'Analytics Showcase',
  '/analytics/tracking': 'Integration Tracking',
  '/analytics/google-callback': 'Google Analytics Callback',
  '/analytics/fire-cycle': 'FIRE Cycle Analytics',
  '/analytics/business-health': 'Business Health',
  '/analytics/cross-platform': 'Cross-Platform Insights',
  '/analytics/digestible-metrics': 'Digestible Metrics',
  '/company-status': 'Company Status',
  '/documents': 'Documents',
  '/user-guide': 'User Guide',
  '/pricing': 'Pricing',
  '/assessment': 'Assessment',
  '/marketplace': 'Marketplace',
  '/integrations': 'Integrations',
  '/integrations/hubspot': 'HubSpot Integration',
  '/integrations/client-intelligence': 'Client Intelligence',
  '/integrations/hubspot/test': 'HubSpot Test',
  '/integrations/hubspot/callback': 'HubSpot Callback',
  '/integrations/microsoft365/callback': 'Microsoft 365 Callback',
  '/integrations/oauth/callback': 'OAuth Callback',
  '/integrations/test-oauth': 'Test OAuth Integration',
  '/integrations/settings': 'Integration Settings',
  '/integrations/setup': 'Integration Setup',
  '/integrations/data-point-mapping': 'Data Point Mapping',
  '/automation': 'Automation',
  '/automation/recipes': 'Automation Recipes',
  '/automation/act': 'Automation Act',
  '/email-intelligence': 'Email Intelligence',
  '/help': 'Help Center',
  '/help/user-guide': 'User Guide',
  '/help/data-usage': 'Data Usage',
  '/help/security-compliance': 'Security & Compliance',
  '/help/about': 'About',
  '/features': 'Features',
  '/admin': 'Admin',
  '/admin/tenant-management': 'Tenant Management',
  // Debug route removed during cleanup
  '/admin/company-settings': 'Company Settings',
  '/admin/account-settings': 'Account Settings',
  '/admin/billing-settings': 'Billing Settings',
  '/admin/integrations-settings': 'Integrations Settings',
  '/admin/security-settings': 'Security Settings',
  '/admin/user-management': 'User Management',
  '/admin/team-settings': 'Team Settings',
  '/admin/profile': 'Profile',
  '/admin/notifications-settings': 'Notifications Settings',
  '/admin/onboarding-checklist': 'Onboarding Checklist',
  '/admin/pricing': 'Pricing',
  '/admin/company-profile': 'Company Profile',
  '/quantum/identity': 'Business Identity',
  '/quantum/identity/profile': 'Company Profile',
  '/quantum/identity/team': 'Team & Culture',
  '/quantum/identity/brand': 'Brand & Values',
  '/business-body': 'Business Body Systems',
  '/admin/billing-dashboard': 'Billing Dashboard',
  '/admin/billing': 'Billing',
  '/admin/appearance-settings': 'Appearance Settings',
  '/admin/assessment': 'Assessment',
  '/admin/profile-settings': 'Profile Settings',
  '/admin/data-privacy-settings': 'Data Privacy Settings',
  '/admin/advanced-settings': 'Advanced Settings',
  '/admin/continuous-improvement': 'Continuous Improvement',
  '/admin/feature-explorer': 'Feature Explorer',
  '/auth/test': 'Authentication Test',
  '/playbook-test': 'Playbook Test',
  '/journey-management': 'Journey Management',
  '/journey/business-identity': 'Business Identity Setup',
  '/auth/signup': 'Sign Up',
  '/admin/ai-model-settings': 'AI Model Settings',
  '/admin/ai-usage': 'AI Usage Monitoring',
  '/admin/login': 'Login',
  '/admin/signup': 'Sign Up',
  '/admin/reset-password': 'Reset Password',
  '/admin/password-reset': 'Password Reset',
  '/admin/auth-callback': 'Auth Callback',
  '/organizations': 'Organizations',
  '/organizations/:orgId': 'Organization Details',
  '/organizations/:orgId/settings': 'Organization Settings',
  '/organizations/:orgId/members': 'Organization Members',
  '/organizations/:orgId/business-profile': 'Organization Business Profile',
  '/admin/auth-status': 'Auth Status',
  '/admin/email-not-verified': 'Email Not Verified',
  '/admin/waitlist': 'Waitlist',
  // FIRE Cycle routes
  '/business/fire-cycle': 'FIRE Cycle Dashboard',
  // Demo routes removed during cleanup
  '/business/fire-cycle/focus': 'Focus Phase',
  '/business/fire-cycle/insight': 'Insight Phase',
  '/business/fire-cycle/roadmap': 'Roadmap Phase',
  '/business/fire-cycle/execute': 'Execute Phase',
  '/business/fire-cycle/goals': 'Business Goals',
  '/journey-intake': 'Journey Intake',
  // Workspace routes
  '/tasks/workspace/actions': 'Action Center',
  '/tasks/workspace/inbox': 'Unified Inbox',
  '/tasks/workspace/calendar': 'Calendar',
  '/tasks/workspace/clients': 'Clients',
  '/ckb': 'Knowledge Base',
  '/workspace/team': 'Team Management',
  '/workspace/customer-insights': 'Customer Insights',
  '/workspace/automation': 'Process Automation',
};

export function getRouteLabel(path: string): string | undefined {
  return ROUTELABELS[path];
} 
