-- Migration: Standardize Integration Data Tables
-- Adds standard columns to all integration data tables for scalability and AI/analytics readiness

-- 1. Email
ALTER TABLE IF EXISTS "public"."Email"
  ADD COLUMN IF NOT EXISTS integration_id TEXT REFERENCES integrations(id),
  ADD COLUMN IF NOT EXISTS source_id TEXT,
  ADD COLUMN IF NOT EXISTS raw_json JSONB,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS external_url TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[];

-- 2. Ticket
ALTER TABLE IF EXISTS "public"."Ticket"
  ADD COLUMN IF NOT EXISTS integration_id TEXT REFERENCES integrations(id),
  ADD COLUMN IF NOT EXISTS source_id TEXT,
  ADD COLUMN IF NOT EXISTS raw_json JSONB,
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS external_url TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[];

-- 3. Task
ALTER TABLE IF EXISTS "public"."Task"
  ADD COLUMN IF NOT EXISTS integration_id TEXT REFERENCES integrations(id),
  ADD COLUMN IF NOT EXISTS source_id TEXT,
  ADD COLUMN IF NOT EXISTS raw_json JSONB,
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS external_url TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[];

-- 4. Note
ALTER TABLE IF EXISTS "public"."Note"
  ADD COLUMN IF NOT EXISTS integration_id TEXT REFERENCES integrations(id),
  ADD COLUMN IF NOT EXISTS source_id TEXT,
  ADD COLUMN IF NOT EXISTS raw_json JSONB,
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS external_url TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[];

-- 5. VARLead
ALTER TABLE IF EXISTS "public"."VARLead"
  ADD COLUMN IF NOT EXISTS integration_id TEXT REFERENCES integrations(id),
  ADD COLUMN IF NOT EXISTS source_id TEXT,
  ADD COLUMN IF NOT EXISTS raw_json JSONB,
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS external_url TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[];

-- 6. Contact
ALTER TABLE IF EXISTS "public"."Contact"
  ADD COLUMN IF NOT EXISTS integration_id TEXT REFERENCES integrations(id),
  ADD COLUMN IF NOT EXISTS source_id TEXT,
  ADD COLUMN IF NOT EXISTS raw_json JSONB,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS external_url TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[];

-- 7. Deal
ALTER TABLE IF EXISTS "public"."Deal"
  ADD COLUMN IF NOT EXISTS integration_id TEXT REFERENCES integrations(id),
  ADD COLUMN IF NOT EXISTS source_id TEXT,
  ADD COLUMN IF NOT EXISTS raw_json JSONB,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS external_url TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[];

-- Add more tables as needed following this pattern. 