name: UX/UI Consistency Check

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  consistency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8 # or your preferred version
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run consistency analysis
      run: pnpm run analyze:consistency
      
    - name: Check consistency score
      run: |
        SCORE=$(node -e "
          const fs = require('fs');
          const report = fs.readFileSync('docs/CONSISTENCY_REPORT.md', 'utf8');
          const scoreMatch = report.match(/Consistency Score:\*\* (\d+\.?\d*)/);
          console.log(scoreMatch ? scoreMatch[1] : '0');
        ")
        echo "Current consistency score: $SCORE"
        if (( $(echo "$SCORE < 7.0" | bc -l) )); then
          echo "❌ Consistency score ($SCORE) is below minimum threshold (7.0)"
          exit 1
        else
          echo "✅ Consistency score ($SCORE) meets requirements"
        fi
        
    - name: Upload consistency report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: consistency-report
        path: docs/CONSISTENCY_REPORT.md
        
    - name: Comment PR with consistency results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('docs/CONSISTENCY_REPORT.md', 'utf8');
          const scoreMatch = report.match(/Consistency Score:\*\* (\d+\.?\d*)/);
          const score = scoreMatch ? scoreMatch[1] : 'Unknown';
          
          const comment = `## 🎯 UX/UI Consistency Check
          
          **Consistency Score:** ${score}/10
          
          ${score >= 7.0 ? '✅ Meets consistency requirements' : '❌ Below minimum threshold (7.0)'}
          
          📊 [View detailed report](../actions/runs/${{ github.run_id }})
          
          ---
          *Automated consistency analysis by Nexus CI*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          }); 