name: Lighthouse CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: |
            --collect.url=https://nexus.marcoby.net/ \
            --collect.url=https://nexus.marcoby.net/marketing-landing \
            --collect.url=https://nexus.marcoby.net/pricing \
            --collect.url=https://nexus.marcoby.net/login \
            --collect.url=https://nexus.marcoby.net/signup \
            --collect.url=https://nexus.marcoby.net/help/privacy-policy \
            --assert.assertions="categories:performance:>=0.8" \
            --assert.assertions="categories:accessibility:>=0.9" \
            --assert.assertions="categories:best-practices:>=0.8" \
            --assert.assertions="categories:seo:>=0.8" 